<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:be.vlaanderen.bodemenondergrond.data.id.graph:codelijst-adertype">
  <xs:simpleType name="be.vlaanderen.bodemenondergrond.data.id.conceptscheme.adertype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/AN" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/BI" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/BL" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/BR" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/CA" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/CD" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/CH" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/CO" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/DO" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/GA" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/GE" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/GI" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/HA" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/HT" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/KA" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/KD" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/KL" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/KO" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/KW" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/MA" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/MI" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/ON" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/PY" />
      <xs:enumeration value="https://data.bodemenondergrond.vlaanderen.be/id/concept/adertype/SU" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
